/**
 * `mycursor schema`
 *
 * Recovers Cursor's protobuf schema from the installed application and writes
 * it beside the configuration.
 *
 * This is what makes the local server able to answer Cursor's own RPC methods
 * rather than only forward them. Cursor's `.proto` files are not published, but
 * its bundles are generated by `@bufbuild/protobuf`, which emits a field table
 * per message and a signature per method — enough to encode and decode
 * anything the client sends.
 *
 * The schema is read from the user's own installation on purpose: no
 * proprietary schema is redistributed, the descriptors always match the
 * installed version, and a Cursor upgrade is handled by re-running this rather
 * than by a release here.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { resolveConfigPaths } from '@mycursor/core/config';
import { extractDescriptors, formatLocateResult, locateInstalls } from '@mycursor/patcher';
import { DescriptorRegistry, type DescriptorDocument } from '@mycursor/protocol/schema';
import { describeSchemaSupport } from '@mycursor/server';

import { detail, fail, heading, info, ok, rows, warn } from '../ui.js';

export interface SchemaFlags {
  /** Print what would be extracted without writing it. */
  dryRun: boolean;
  /** Re-extract even when the document already matches the installed version. */
  force: boolean;
}

export async function schema(flags: SchemaFlags): Promise<number> {
  heading('mycursor schema');

  const located = locateInstalls();
  const install = located.installs.find((entry) => entry.kind === 'desktop') ?? located.installs[0];
  if (!install) {
    fail('no Cursor installation found');
    console.log(`\n${formatLocateResult(located)}`);
    return 1;
  }

  const paths = resolveConfigPaths();
  info(`source  ${install.root}`);
  info(`Cursor  ${install.version}`);

  const existing = readExisting(paths.descriptors);
  if (existing && existing.cursorVersion === install.version && !flags.force) {
    ok(`descriptors already match Cursor ${install.version}`);
    reportSupport(describe(existing));
    detail('use --force to re-extract');
    return 0;
  }
  if (existing && existing.cursorVersion !== install.version) {
    warn(`stored descriptors are from Cursor ${existing.cursorVersion}; re-extracting`);
  }

  const started = Date.now();
  const report = extractDescriptors(install);
  const elapsed = Date.now() - started;

  if (Object.keys(report.document.messages).length === 0) {
    fail('no protobuf schema was found in this installation');
    for (const warning of report.warnings) detail(warning);
    detail('this build may not use @bufbuild/protobuf code generation');
    return 1;
  }

  ok(`extracted in ${elapsed} ms from ${report.sources.length} bundle(s)`);
  for (const source of report.sources) detail(source);
  const registry = describe(report.document);

  rows([
    ['message sites', String(report.messageSites)],
    ['enum sites', String(report.enumSites)],
    ['service sites', String(report.serviceSites)],
    ['unparsed sites', String(report.skippedSites)],
    ['unresolved refs', String(report.unresolvedReferences)],
  ]);
  for (const warning of report.warnings) warn(warning);

  if (report.unresolvedReferences > 0) {
    // Unresolved references degrade to opaque bytes rather than failing, so
    // this is reported as information.
    detail('unresolved references are carried as opaque bytes and round trip unchanged');
  }

  reportSupport(registry);

  if (flags.dryRun) {
    info('dry run: nothing was written');
    return 0;
  }

  writeDocument(paths.descriptors, report.document);
  ok(`wrote ${paths.descriptors}`);
  detail('restart "mycursor serve" to pick it up, or it will be loaded on next start');
  return 0;
}

/**
 * Reports which server features this schema can actually back.
 *
 * A partial extraction is the outcome worth being loud about: it writes a
 * file and reports success, then leaves the affected features quietly
 * forwarding to the official API, which presents as "BYOK does not work"
 * with nothing pointing at the cause.
 */
function reportSupport(registry: DescriptorRegistry): void {
  const support = describeSchemaSupport(registry);
  console.log();
  for (const feature of support) {
    if (feature.supported) ok(feature.label);
    else warn(`${feature.label} — unavailable, ${feature.missing.length} type(s) missing`);
    for (const type of feature.missing.slice(0, 4)) detail(type);
  }
  if (support.some((feature) => !feature.supported)) {
    detail('these fall back to the official API; the rest still work');
    detail('please report the Cursor version so extraction can be taught this build');
  }
}

function describe(document: DescriptorDocument): DescriptorRegistry {
  const registry = DescriptorRegistry.fromDocument(document);
  const stats = registry.stats();
  rows([
    ['messages', String(stats.messages)],
    ['enums', String(stats.enums)],
    ['services', String(stats.services)],
    ['methods', String(stats.methods)],
    ['dangling type refs', String(stats.danglingReferences)],
  ]);
  return registry;
}

function readExisting(path: string): DescriptorDocument | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf-8')) as DescriptorDocument;
  } catch {
    return null;
  }
}

/** Writes atomically: the document is several megabytes and the server watches it. */
function writeDocument(path: string, document: DescriptorDocument): void {
  mkdirSync(dirname(path), { recursive: true });
  const temp = join(dirname(path), `.descriptors.${process.pid}.tmp`);
  writeFileSync(temp, JSON.stringify(document), 'utf-8');
  renameSync(temp, path);
}
