/**
 * Recovering Cursor's protobuf schema from the installed application.
 *
 * Cursor's bundles are generated by `@bufbuild/protobuf`, whose code generator
 * emits every message as a field table and every enum as a value table:
 *
 *   VAR = ns.makeMessageType("aiserver.v1.Foo", () => [
 *     { no: 1, name: "bar", kind: "scalar", T: 9 },
 *     { no: 2, name: "baz", kind: "message", T: OTHER_VAR, repeated: !0 },
 *   ])
 *   VAR = ns.makeEnum("aiserver.v1.Kind", [{ no: 0, name: "UNSPECIFIED" }])
 *
 * Extracting these gives the complete schema without the `.proto` files.
 *
 * Reading it from the user's own installation rather than shipping a copy is a
 * deliberate choice: no proprietary schema enters this repository, the
 * descriptors always match the installed version, and a Cursor upgrade is
 * handled by re-extracting rather than by a release here.
 *
 * References inside a field table point at minified variables, so extraction
 * is two-pass: bind every variable to its type name first, then resolve.
 *
 * Crucially, resolution happens **per bundle**. Each bundle is minified
 * independently, so the same short identifier means different types in
 * different files — `ln` is one message in the renderer and another in the
 * agent host. Sharing one variable map across bundles silently resolves some
 * references to the wrong type, which is the kind of error that produces a
 * response the client misparses rather than an outright failure.
 */

import { existsSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

import {
  toJsonName,
  type DescriptorDocument,
  type EnumValueDescriptor,
  type FieldDescriptor,
  type MapValueDescriptor,
  type MethodDescriptor,
  type MethodKind,
  type ScalarTypeNumber,
} from '@mycursor/protocol/schema';

import type { InstallLayout } from '../detect/layout.js';
import {
  matchBracket,
  parseArray,
  parseObject,
  readIdentifierBackwards,
  referencedIdentifier,
  tryReadStringLiteral,
  skipWhitespace,
  type LiteralValue,
} from './bundle-scanner.js';

const MESSAGE_MARKER = 'makeMessageType';
const ENUM_MARKER = 'makeEnum';

/**
 * A second code generation form.
 *
 * `@bufbuild/protobuf` emits its own well-known types — `Timestamp`,
 * `Duration`, `Struct`, `Value` — as classes with static members rather than
 * through `makeMessageType`:
 *
 *   Rm.typeName = "google.protobuf.Timestamp";
 *   Rm.fields = e.util.newFieldList(() => [{ no: 1, name: "seconds", ... }]);
 *
 * Missing this form leaves every field that references a well-known type
 * unresolved, which is what stops `google.protobuf.Value` — and therefore MCP
 * tool arguments — from being encodable.
 */
const CLASS_TYPE_NAME_MARKER = '.typeName=';
const FIELD_LIST_MARKER = 'newFieldList';

/**
 * Service definitions are plain object literals rather than factory calls:
 *
 *   VAR = { typeName: "aiserver.v1.AiService", methods: {
 *     availableModels: { name: "AvailableModels", I: REQ, O: RES, kind: k.Unary } } }
 */
const SERVICE_MARKER = 'typeName:';

/** `MethodKind` member names, as the minified code spells them. */
const METHOD_KINDS: Record<string, MethodKind> = {
  Unary: 'unary',
  ServerStreaming: 'server-stream',
  ClientStreaming: 'client-stream',
  BiDiStreaming: 'bidi',
};

/** A fully-qualified protobuf type name, e.g. `aiserver.v1.Foo.Bar`. */
const TYPE_NAME = /^[a-z][a-z0-9_]*(\.[a-z0-9_]+)*(\.[A-Z][A-Za-z0-9_]*)+$/;

/**
 * Bundles worth scanning, most complete first.
 *
 * The utility process and the extension host carry the same generated code as
 * the renderer but are an order of magnitude smaller, so scanning them is
 * faster and yields the same messages.
 */
const CANDIDATE_BUNDLES = [
  'out/vs/code/electron-utility/alwaysLocalSingleton/alwaysLocalSingletonMain.js',
  'out/vs/workbench/api/node/extensionHostProcess.js',
  'out/vs/workbench/workbench.desktop.main.js',
  'out/vs/workbench/workbench.glass.main.js',
  'extensions/cursor-agent-host/dist/main.js',
];

export interface ExtractionReport {
  document: DescriptorDocument;
  /** Bundles that were read, in order. */
  sources: string[];
  messageSites: number;
  enumSites: number;
  serviceSites: number;
  /** Sites whose field table could not be parsed. */
  skippedSites: number;
  /** Field references that no extracted type satisfies. */
  unresolvedReferences: number;
  warnings: string[];
}

interface RawMessage {
  typeName: string;
  fields: LiteralValue[];
}

/**
 * Extracts descriptors from an installation.
 *
 * Several bundles are scanned and merged: each contains the messages its own
 * process needs, and the union is what the server may be asked to handle.
 */
export function extractDescriptors(layout: InstallLayout): ExtractionReport {
  const warnings: string[] = [];
  const sources: string[] = [];

  const messages: Record<string, FieldDescriptor[]> = {};
  const enums = new Map<string, EnumValueDescriptor[]>();
  const services: Record<string, Record<string, MethodDescriptor>> = {};

  let messageSites = 0;
  let enumSites = 0;
  let serviceSites = 0;
  let skippedSites = 0;
  let unresolved = 0;

  for (const relative of CANDIDATE_BUNDLES) {
    const path = join(layout.root, relative);
    if (!existsSync(path)) continue;

    let source: string;
    try {
      source = readFileSync(path, 'utf-8');
    } catch (error) {
      warnings.push(`could not read ${relative}: ${(error as Error).message}`);
      continue;
    }
    if (!source.includes(MESSAGE_MARKER)) continue;
    sources.push(relative);

    const scan = scanBundle(source);
    messageSites += scan.messageSites;
    enumSites += scan.enumSites;
    serviceSites += scan.serviceSites;
    skippedSites += scan.skippedSites;

    // Resolve with this bundle's own variable map, before merging.
    for (const message of scan.messages) {
      if (message.typeName in messages) continue;
      const fields: FieldDescriptor[] = [];
      for (const raw of message.fields) {
        const field = toFieldDescriptor(raw, scan.variableToType);
        if (!field) continue;
        if (field.unresolved) unresolved += 1;
        fields.push(field.descriptor);
      }
      // Field number order makes the document readable and diffable.
      fields.sort((a, b) => a.no - b.no);
      messages[message.typeName] = fields;
    }

    for (const [typeName, values] of scan.enums) {
      if (!enums.has(typeName)) enums.set(typeName, values);
    }

    // Services are resolved with the same bundle's variable map, for the same
    // reason the fields are.
    for (const service of scan.services) {
      if (service.typeName in services) continue;
      const methods: Record<string, MethodDescriptor> = {};
      for (const method of service.methods) {
        const input = scan.variableToType.get(method.inputRef);
        const output = scan.variableToType.get(method.outputRef);
        if (!input || !output) {
          unresolved += 1;
          continue;
        }
        methods[method.name] = { name: method.name, kind: method.kind, input, output };
      }
      if (Object.keys(methods).length > 0) services[service.typeName] = methods;
    }
  }

  if (sources.length === 0) {
    warnings.push('no bundle in this installation contained generated protobuf code');
  }

  const document: DescriptorDocument = {
    $schemaVersion: 1,
    cursorVersion: layout.version,
    source: sources.join(', ') || 'none',
    extractedAt: new Date().toISOString(),
    messages,
    enums: Object.fromEntries(enums),
    services,
  };

  return {
    document,
    sources,
    messageSites,
    enumSites,
    serviceSites,
    skippedSites,
    unresolvedReferences: unresolved,
    warnings,
  };
}

interface RawService {
  typeName: string;
  methods: { name: string; kind: MethodKind; inputRef: string; outputRef: string }[];
}

interface BundleScan {
  variableToType: Map<string, string>;
  messages: RawMessage[];
  enums: Map<string, EnumValueDescriptor[]>;
  services: RawService[];
  messageSites: number;
  enumSites: number;
  serviceSites: number;
  skippedSites: number;
}

function scanBundle(source: string): BundleScan {
  const variableToType = new Map<string, string>();
  const messages: RawMessage[] = [];
  const enums = new Map<string, EnumValueDescriptor[]>();
  let messageSites = 0;
  let enumSites = 0;
  let skippedSites = 0;

  const visit = (
    marker: string,
    handler: (typeName: string, afterName: number) => boolean,
  ): number => {
    let from = 0;
    let sites = 0;
    for (;;) {
      const index = source.indexOf(marker, from);
      if (index === -1) break;
      from = index + marker.length;

      let cursor = skipWhitespace(source, index + marker.length);
      if (source[cursor] !== '(') continue;
      cursor = skipWhitespace(source, cursor + 1);
      if (source[cursor] !== '"' && source[cursor] !== "'") continue;

      const read = tryReadStringLiteral(source, cursor);
      if (!read) continue;
      const { value: typeName, end } = read;
      if (!TYPE_NAME.test(typeName)) continue;
      sites += 1;

      // The variable this type is assigned to, so references resolve later.
      const assignment = source.lastIndexOf('=', index);
      if (assignment !== -1 && index - assignment < 40) {
        const variable = readIdentifierBackwards(source, assignment);
        if (variable) variableToType.set(variable, typeName);
      }

      if (!handler(typeName, end)) skippedSites += 1;
    }
    return sites;
  };

  messageSites = visit(MESSAGE_MARKER, (typeName, afterName) => {
    // `() => [ ... ]` follows the type name.
    const arrow = source.indexOf('=>', afterName);
    if (arrow === -1 || arrow - afterName > 40) return false;
    const bracket = source.indexOf('[', arrow);
    if (bracket === -1 || bracket - arrow > 8) return false;
    const end = matchBracket(source, bracket);
    if (end === -1) return false;
    try {
      messages.push({ typeName, fields: parseArray(source.slice(bracket, end), 0).value });
      return true;
    } catch {
      return false;
    }
  });

  enumSites = visit(ENUM_MARKER, (typeName, afterName) => {
    const bracket = source.indexOf('[', afterName);
    if (bracket === -1 || bracket - afterName > 10) return false;
    const end = matchBracket(source, bracket);
    if (end === -1) return false;
    try {
      const entries = parseArray(source.slice(bracket, end), 0).value;
      const values: EnumValueDescriptor[] = [];
      for (const entry of entries) {
        if (!entry || typeof entry !== 'object' || Array.isArray(entry)) continue;
        const record = entry as Record<string, LiteralValue>;
        if (typeof record['no'] !== 'number' || typeof record['name'] !== 'string') continue;
        values.push({ no: record['no'], name: record['name'] });
      }
      enums.set(typeName, values);
      return true;
    } catch {
      return false;
    }
  });

  // The class form, and the aliases that make its bindings reachable.
  messageSites += scanClassMessages(source, variableToType, messages);
  followAliases(source, variableToType);

  const services = scanServices(source);

  return {
    variableToType,
    messages,
    enums,
    services,
    messageSites,
    enumSites,
    serviceSites: services.length,
    skippedSites,
  };
}

/**
 * Extracts messages emitted as classes with static `typeName` and `fields`.
 *
 * The two statements are adjacent in the generated code, so the field list is
 * looked for in a window after the name rather than by parsing the class.
 */
function scanClassMessages(
  source: string,
  variableToType: Map<string, string>,
  messages: RawMessage[],
): number {
  const WINDOW = 400;
  let from = 0;
  let sites = 0;

  for (;;) {
    const index = source.indexOf(CLASS_TYPE_NAME_MARKER, from);
    if (index === -1) break;
    from = index + CLASS_TYPE_NAME_MARKER.length;

    let cursor = skipWhitespace(source, index + CLASS_TYPE_NAME_MARKER.length);
    if (source[cursor] !== '"' && source[cursor] !== "'") continue;
    const read = tryReadStringLiteral(source, cursor);
    if (!read) continue;
    const { value: typeName, end } = read;
    if (!TYPE_NAME.test(typeName)) continue;

    const variable = readIdentifierBackwards(source, index);
    if (!variable) continue;

    const fieldsAt = source.indexOf(`${variable}.fields`, end);
    if (fieldsAt === -1 || fieldsAt - end > WINDOW) continue;
    const listAt = source.indexOf(FIELD_LIST_MARKER, fieldsAt);
    if (listAt === -1 || listAt - fieldsAt > 40) continue;
    const bracket = source.indexOf('[', listAt);
    if (bracket === -1 || bracket - listAt > 40) continue;
    const bracketEnd = matchBracket(source, bracket);
    if (bracketEnd === -1) continue;

    sites += 1;
    if (!variableToType.has(variable)) variableToType.set(variable, typeName);
    try {
      messages.push({ typeName, fields: parseArray(source.slice(bracket, bracketEnd), 0).value });
    } catch {
      continue;
    }
  }

  return sites;
}

/**
 * Binds simple aliases of a type variable.
 *
 * The class form ends with `var y = Rm`, and other modules reference the
 * alias rather than the original. Without following them, every field
 * pointing at a well-known type stays unresolved. One hop is enough for the
 * shapes the generator produces, and repeating it converges immediately.
 */
function followAliases(source: string, variableToType: Map<string, string>): void {
  const ALIAS = /(?:var|let|const)\s+([A-Za-z0-9_$]+)\s*=\s*([A-Za-z0-9_$]+)\s*[;,\n]/g;
  for (let pass = 0; pass < 2; pass += 1) {
    let added = 0;
    ALIAS.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = ALIAS.exec(source))) {
      const [, alias, target] = match;
      if (!alias || !target || variableToType.has(alias)) continue;
      const typeName = variableToType.get(target);
      if (!typeName) continue;
      variableToType.set(alias, typeName);
      added += 1;
    }
    if (added === 0) break;
  }
}

/**
 * Extracts service definitions.
 *
 * These are object literals, so the scan looks for a `typeName` whose sibling
 * is a `methods` object. `SERVICE_MARKER` also matches message type tables, so
 * the `methods` check is what distinguishes the two.
 */
function scanServices(source: string): RawService[] {
  const services: RawService[] = [];
  let from = 0;

  for (;;) {
    const index = source.indexOf(SERVICE_MARKER, from);
    if (index === -1) break;
    from = index + SERVICE_MARKER.length;

    let cursor = skipWhitespace(source, index + SERVICE_MARKER.length);
    if (source[cursor] !== '"' && source[cursor] !== "'") continue;
    const read = tryReadStringLiteral(source, cursor);
    if (!read) continue;
    const { value: typeName, end } = read;
    if (!TYPE_NAME.test(typeName)) continue;

    cursor = skipWhitespace(source, end);
    if (source[cursor] !== ',') continue;
    cursor = skipWhitespace(source, cursor + 1);
    if (!source.startsWith('methods:', cursor)) continue;

    cursor = skipWhitespace(source, cursor + 'methods:'.length);
    if (source[cursor] !== '{') continue;
    const bodyEnd = matchBracket(source, cursor);
    if (bodyEnd === -1) continue;

    let parsed: Record<string, LiteralValue>;
    try {
      parsed = parseObject(source.slice(cursor, bodyEnd), 0).value;
    } catch {
      continue;
    }

    const methods: RawService['methods'] = [];
    for (const entry of Object.values(parsed)) {
      if (!entry || typeof entry !== 'object' || Array.isArray(entry)) continue;
      const record = entry as Record<string, LiteralValue>;
      const name = record['name'];
      const inputRef = referencedIdentifier(record['I']);
      const outputRef = referencedIdentifier(record['O']);
      const kindRef = referencedIdentifier(record['kind']);
      if (typeof name !== 'string' || !inputRef || !outputRef) continue;

      // `kind` is a member expression such as `k.ServerStreaming`; only the
      // trailing member matters.
      const kindName = (kindRef ?? '').split('.').pop() ?? 'Unary';
      methods.push({
        name,
        kind: METHOD_KINDS[kindName] ?? 'unary',
        inputRef,
        outputRef,
      });
    }

    if (methods.length > 0) services.push({ typeName, methods });
  }

  return services;
}

function toFieldDescriptor(
  raw: LiteralValue,
  variableToType: Map<string, string>,
): { descriptor: FieldDescriptor; unresolved: boolean } | null {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const record = raw as Record<string, LiteralValue>;

  const no = record['no'];
  const name = record['name'];
  const kind = record['kind'];
  if (typeof no !== 'number' || typeof name !== 'string' || typeof kind !== 'string') return null;

  const descriptor: FieldDescriptor = {
    no,
    name,
    jsonName: toJsonName(name),
    kind: kind as FieldDescriptor['kind'],
  };
  if (record['repeated'] === true) descriptor.repeated = true;
  if (record['opt'] === true) descriptor.optional = true;
  if (typeof record['oneof'] === 'string') descriptor.oneof = record['oneof'];

  let unresolved = false;

  if (kind === 'scalar') {
    descriptor.scalar = (typeof record['T'] === 'number' ? record['T'] : 9) as ScalarTypeNumber;
  } else if (kind === 'message' || kind === 'enum') {
    const identifier = referencedIdentifier(record['T']);
    const resolved = identifier ? variableToType.get(identifier) : undefined;
    if (resolved) descriptor.typeName = resolved;
    else unresolved = true;
  } else if (kind === 'map') {
    const key = (typeof record['K'] === 'number' ? record['K'] : 9) as ScalarTypeNumber;
    const valueSpec = record['V'];
    const value: MapValueDescriptor = { kind: 'scalar', scalar: 9 as ScalarTypeNumber };
    if (valueSpec && typeof valueSpec === 'object' && !Array.isArray(valueSpec)) {
      const valueRecord = valueSpec as Record<string, LiteralValue>;
      const valueKind = valueRecord['kind'];
      if (valueKind === 'message' || valueKind === 'enum') {
        value.kind = valueKind;
        const identifier = referencedIdentifier(valueRecord['T']);
        const resolved = identifier ? variableToType.get(identifier) : undefined;
        if (resolved) value.typeName = resolved;
        else unresolved = true;
        delete value.scalar;
      } else {
        value.kind = 'scalar';
        value.scalar = (typeof valueRecord['T'] === 'number' ? valueRecord['T'] : 9) as ScalarTypeNumber;
      }
    }
    descriptor.map = { key, value };
  } else {
    // An unrecognised kind would be silently mis-encoded, so it is dropped.
    return null;
  }

  return { descriptor, unresolved };
}

/** Rough size of the bundles that would be scanned, for progress reporting. */
export function estimateScanBytes(layout: InstallLayout): number {
  let total = 0;
  for (const relative of CANDIDATE_BUNDLES) {
    const path = join(layout.root, relative);
    if (!existsSync(path)) continue;
    try {
      total += statSync(path).size;
    } catch {
      continue;
    }
  }
  return total;
}

export { CANDIDATE_BUNDLES };
